name: zoom_clone
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.7
  firebase_auth: ^3.8.0
  firebase_core: ^1.22.0
  flutter:
    sdk: flutter
  google_sign_in: ^5.4.1
  intl: ^0.17.0
  jitsi_meet: ^4.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
