// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCVGZddFBByURF_QQLXkDnPM80FA07Nlo',
    appId: '1:350553146378:web:309ea1973ecdea52f3cbf3',
    messagingSenderId: '350553146378',
    projectId: 'zoom-clone-a2a10',
    authDomain: 'zoom-clone-a2a10.firebaseapp.com',
    storageBucket: 'zoom-clone-a2a10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6j3uPQdv5DX0jfqtVvlKPSjHk4D5149Q',
    appId: '1:350553146378:android:bd9cea9ea163efbcf3cbf3',
    messagingSenderId: '350553146378',
    projectId: 'zoom-clone-a2a10',
    storageBucket: 'zoom-clone-a2a10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCbg0eg1h4Sl0EdkcoEgxZ2apWDKT9ZnQ',
    appId: '1:350553146378:ios:6fe93f7b44a17873f3cbf3',
    messagingSenderId: '350553146378',
    projectId: 'zoom-clone-a2a10',
    storageBucket: 'zoom-clone-a2a10.appspot.com',
    iosClientId: '350553146378-h02ivpfqqbajo356n2c2c1kepbq0geta.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCbg0eg1h4Sl0EdkcoEgxZ2apWDKT9ZnQ',
    appId: '1:350553146378:ios:6fe93f7b44a17873f3cbf3',
    messagingSenderId: '350553146378',
    projectId: 'zoom-clone-a2a10',
    storageBucket: 'zoom-clone-a2a10.appspot.com',
    iosClientId: '350553146378-h02ivpfqqbajo356n2c2c1kepbq0geta.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );
}
